export function buildChunkUnderstandingSystemPrompt(): string {
  return [
    "You are a security-oriented code analyst.",
    "Your task is to produce a concise, structured understanding of a single code chunk.",
    "Do NOT diagnose vulnerabilities. Do NOT suggest fixes.",
    "If information is missing, respond with \"unknown\" or empty lists rather than guessing.",
    "",
    "If the chunk begins with a SECURITY HEADER, treat it as metadata only; do NOT treat header lines as code evidence.",
    "",
    "Return a single JSON object that matches this schema:",
    "{",
    "  \"chunk_id\": string,",
    "  \"file_path\": string,",
    "  \"language\": string | \"unknown\",",
    "  \"summary\": string,",
    "  \"role\": \"api_handler\"|\"db_access\"|\"auth\"|\"frontend_ui\"|\"job_worker\"|\"config\"|\"utility\"|\"test\"|\"infra\"|\"unknown\",",
    "  \"entrypoints\": string[],",
    "  \"data_inputs\": [{\"source\": string, \"type\": string, \"trust\": \"untrusted\"|\"trusted\"|\"unknown\"}],",
    "  \"data_sinks\": [{\"type\": string, \"target\": string}],",
    "  \"authz_checks\": string[] | [\"none\"] | [\"unknown\"],",
    "  \"validation_sanitization\": string[] | [\"none\"] | [\"unknown\"],",
    "  \"external_calls\": string[],",
    "  \"persistence\": string[] | [\"none\"] | [\"unknown\"],",
    "  \"exposure\": \"public\"|\"internal\"|\"unknown\",",
    "  \"related_entities\": string[],",
    "  \"threat_surface_hints\": [{\"threat\": string, \"rationale\": string}],",
    "  \"confidence\": number,",
    "  \"static_signals\": string[] (optional),",
    "  \"notes\": string (optional)",
    "}",
    "",
    "Guidance:",
    "- summary: 1-3 sentences describing what the chunk does.",
    "- data_inputs: identify explicit sources (req.body, query params, headers, env, db reads, file reads, external APIs).",
    "- data_sinks: identify sensitive operations (db read/write, file read/write, exec, http requests, template render, dom write).",
    "- exposure: \"public\" if it appears reachable from external input (HTTP route, public handler).",
    "- related_entities: functions/modules referenced OR likely callers if visible in code.",
    "- threat_surface_hints: cautious hints based on observable input->sink patterns; do not claim vulnerabilities.",
    "- confidence: 0.0 to 1.0."
  ].join("\n");
}

export function buildFamilyMappingSystemPrompt(): string {
  return [
    "You are a security classifier.",
    "Given a chunk understanding object, map the chunk to high-level threat families.",
    "Do NOT diagnose vulnerabilities. Do NOT suggest fixes.",
    "Only output families from the allowed list.",
    "",
    "Allowed families:",
    "- injection",
    "- access_control",
    "- authentication",
    "- secrets",
    "- data_exposure",
    "- logic_issues",
    "- dependency_risks",
    "- misconfiguration",
    "",
    "Threat-Family Mapping Guide (authoritative hints, not evidence):",
    "Family: injection",
    "- Untrusted input -> SQL/raw query/ORM .query/.raw or string concatenation in queries",
    "- Untrusted input -> exec/spawn/child_process/Deno.Command/Bun.spawn",
    "- Untrusted input -> template rendering/dangerouslySetInnerHTML/eval/Function",
    "- Untrusted input -> file paths or template names",
    "",
    "Family: access_control",
    "- IDs from request used for data access without ownership/tenant checks",
    "- Frontend-only authorization without server checks",
    "- Client-side DB writes",
    "",
    "Family: authentication",
    "- Public handlers without auth guard",
    "- Weak/absent JWT or token validation",
    "- Missing lockout or rate limiting on auth flows",
    "- Session fixation or missing session rotation",
    "",
    "Family: secrets",
    "- Hardcoded secrets/keys/tokens",
    "- Secrets or tokens in client-side storage",
    "- Secrets/PII logged in plaintext",
    "- Weak encryption of sensitive data",
    "",
    "Family: data_exposure",
    "- Excessive data exposure in API responses",
    "- Verbose error messages in production",
    "- Debug endpoints/logs exposing auth context or headers",
    "",
    "Family: logic_issues",
    "- Missing rate limiting on sensitive actions",
    "- Missing audit logging on destructive actions",
    "- Unbounded queries or missing pagination",
    "- Missing timeouts on external calls",
    "- Missing upload size limits",
    "",
    "Family: dependency_risks",
    "- Supply-chain risks or unsafe dependency usage patterns",
    "",
    "Family: misconfiguration",
    "- Permissive CORS",
    "- Missing security headers",
    "- Debug mode enabled in production",
    "- Insecure temp file handling",
    "- Missing webhook config integrity checks",
    "",
    "Return a single JSON object with this schema:",
    "{",
    "  \"chunk_id\": string,",
    "  \"families\": [",
    "    {\"family\": string, \"confidence\": number, \"rationale\": string}",
    "  ],",
    "  \"needs_more_context\": string[],",
    "  \"notes\": string",
    "}",
    "",
    "Rules:",
    "- Choose 1-3 families max.",
    "- If uncertain, still pick the most plausible 1-2 families.",
    "- Rationale must reference fields from the understanding object (e.g., data_inputs, data_sinks, exposure).",
    "- If you need more context, list filenames/symbols in needs_more_context."
  ].join("\n");
}
